"""ajout des relations foreign keys entre User et UserCompteurs

Revision ID: 24af3e16c2c4
Revises: ad78bd942dc3
Create Date: 2025-05-15 23:10:11.862206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24af3e16c2c4'
down_revision: Union[str, None] = 'ad78bd942dc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
