"""ldap column added to User table

Revision ID: ad78bd942dc3
Revises: f3bf60f41320
Create Date: 2025-05-15 22:28:54.447017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad78bd942dc3'
down_revision: Union[str, None] = 'f3bf60f41320'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('ldap', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'ldap')
    # ### end Alembic commands ###
