"""initial clean migration

Revision ID: f3bf60f41320
Revises: 
Create Date: 2025-05-13 21:23:27.792388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3bf60f41320'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seuils_tarifs')
    op.add_column('seuil_tarif', sa.Column('id_seuil', sa.Integer(), nullable=True))
    op.add_column('seuil_tarif', sa.Column('kwh_min', sa.Double(), nullable=False))
    op.add_column('seuil_tarif', sa.Column('kwh_max', sa.Double(), nullable=False))
    op.add_column('seuil_tarif', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('user_session', 'expires_at')
    op.drop_column('user_session', 'jti')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_session', sa.Column('jti', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_session', sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('seuil_tarif', 'created_at')
    op.drop_column('seuil_tarif', 'kwh_max')
    op.drop_column('seuil_tarif', 'kwh_min')
    op.drop_column('seuil_tarif', 'id_seuil')
    op.create_table('seuils_tarifs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code_tarif', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('id_seuil', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('kwh_min', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('kwh_max', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='seuils_tarifs_pkey')
    )
    # ### end Alembic commands ###
