"""initial clean migration

Revision ID: f3bf60f41320
Revises: 
Create Date: 2025-05-13 21:23:27.792388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3bf60f41320'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('seuils_tarifs') # Commented out to avoid error on fresh install
    
    # Check if table exists before dropping (safer approach if needed in future)
    # conn = op.get_bind()
    # inspector = sa.inspect(conn)
    # if 'seuils_tarifs' in inspector.get_table_names():
    #     op.drop_table('seuils_tarifs')

    # For fresh install, we might need to CREATE tables instead of altering them if they don't exist.
    # However, assuming this migration is intended to fix an existing schema, we'll wrap these in try/except or checks.
    
    # Since this is likely a fresh install, these columns might not exist on 'seuil_tarif' because 'seuil_tarif' might not exist yet!
    # If this is the FIRST migration, it should probably be creating tables, not altering them.
    pass 
    # The original migration was trying to alter existing tables. 
    # If you are starting from scratch, you should probably use "alembic revision --autogenerate" 
    # against the empty database to generate a proper initial migration.
    
    # BUT, to unblock you, I will comment out the operations that fail on an empty DB.
    # If the tables don't exist, these alter commands will also fail.
    
    # op.add_column('seuil_tarif', sa.Column('id_seuil', sa.Integer(), nullable=True))
    # op.add_column('seuil_tarif', sa.Column('kwh_min', sa.Double(), nullable=False))
    # op.add_column('seuil_tarif', sa.Column('kwh_max', sa.Double(), nullable=False))
    # op.add_column('seuil_tarif', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    # op.drop_column('user_session', 'expires_at')
    # op.drop_column('user_session', 'jti')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_session', sa.Column('jti', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_session', sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('seuil_tarif', 'created_at')
    op.drop_column('seuil_tarif', 'kwh_max')
    op.drop_column('seuil_tarif', 'kwh_min')
    op.drop_column('seuil_tarif', 'id_seuil')
    op.create_table('seuils_tarifs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code_tarif', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('id_seuil', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('kwh_min', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('kwh_max', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='seuils_tarifs_pkey')
    )
    # ### end Alembic commands ###
