"""Ajout des relations explicites avec foreign_keys

Revision ID: fe54b0f7ada6
Revises: 24af3e16c2c4
Create Date: 2025-05-15 23:18:36.075424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe54b0f7ada6'
down_revision: Union[str, None] = '24af3e16c2c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
