#!/bin/bash
# Script de démarrage rapide - Affiche les commandes à exécuter

echo "=========================================="
echo "Déploiement SamaConso - Guide Rapide"
echo "=========================================="
echo ""
echo "Ce script affiche les commandes à exécuter sur chaque serveur."
echo "Copiez et exécutez les commandes appropriées sur chaque serveur."
echo ""
echo "=========================================="
echo "1. PRÉPARATION (sur votre machine locale)"
echo "=========================================="
echo ""
echo "# Créer une archive du projet"
echo "tar -czf samaconso-deployment.tar.gz \\"
echo "    --exclude='venv' \\"
echo "    --exclude='__pycache__' \\"
echo "    --exclude='*.pyc' \\"
echo "    --exclude='.git' \\"
echo "    ."
echo ""
echo "# Transférer vers les serveurs"
echo "scp samaconso-deployment.tar.gz user@10.101.1.57:/tmp/"
echo "scp samaconso-deployment.tar.gz user@10.101.1.210:/tmp/"
echo "scp samaconso-deployment.tar.gz user@10.101.1.211:/tmp/"
echo ""
echo "scp -r deployment/ user@10.101.1.57:/tmp/"
echo "scp -r deployment/ user@10.101.1.210:/tmp/"
echo "scp -r deployment/ user@10.101.1.211:/tmp/"
echo ""
echo "=========================================="
echo "2. SRV-MOBAPPBD (10.101.1.57)"
echo "=========================================="
echo ""
echo "ssh user@10.101.1.57"
echo "cd /tmp"
echo "tar -xzf samaconso-deployment.tar.gz"
echo "cd deployment/scripts"
echo "chmod +x *.sh"
echo "sudo bash setup-db-server.sh"
echo "sudo bash deploy-db.sh"
echo ""
echo "=========================================="
echo "3. SRV-MOBAPP1 (10.101.1.210)"
echo "=========================================="
echo ""
echo "ssh user@10.101.1.210"
echo "cd /tmp"
echo "tar -xzf samaconso-deployment.tar.gz"
echo "cd deployment/scripts"
echo "chmod +x *.sh"
echo "sudo bash setup-app-server.sh SRV-MOBAPP1 10.101.1.210 10.101.1.57"
echo "sudo bash deploy-app.sh SRV-MOBAPP1 10.101.1.210 10.101.1.57"
echo "sudo bash setup-nginx-lb.sh"
echo ""
echo "=========================================="
echo "4. SRV-MOBAPP2 (10.101.1.211)"
echo "=========================================="
echo ""
echo "ssh user@10.101.1.211"
echo "cd /tmp"
echo "tar -xzf samaconso-deployment.tar.gz"
echo "cd deployment/scripts"
echo "chmod +x *.sh"
echo "sudo bash setup-app-server.sh SRV-MOBAPP2 10.101.1.211 10.101.1.57"
echo "sudo bash deploy-app.sh SRV-MOBAPP2 10.101.1.211 10.101.1.57"
echo ""
echo "=========================================="
echo "5. VÉRIFICATION"
echo "=========================================="
echo ""
echo "# Vérifier la santé de tous les services"
echo "bash deployment/scripts/health-check.sh"
echo ""
echo "# Tester l'API"
echo "curl http://10.101.1.210/health"
echo "curl http://10.101.1.211:8000/health"
echo ""
echo "=========================================="
echo "6. INITIALISATION BASE DE DONNÉES"
echo "=========================================="
echo ""
echo "# Sur SRV-MOBAPP1 ou SRV-MOBAPP2"
echo "cd /opt/samaconso"
echo "docker-compose exec api alembic upgrade head"
echo ""
echo "=========================================="
echo "Déploiement terminé!"
echo "=========================================="

